### ISSUE TITLE
mix compile fails 

### ISSUE THREAD

**Issue by jmedding** [Hermanverschooten/gpio_rpi#2]
I have elixir and erlang freshly installed on an Rpi2 with raspian Jesse.

```
pi@raspberrypi:~/gpio_rpi $ elixir -v
Erlang/OTP 18 [erts-7.3] [source] [smp:4:4] [async-threads:10] [kernel-poll:false]

Elixir 1.3.3
```

I did a fresh clone, cd'd into the dir and `mix compile`

```
pi@raspberrypi:~/gpio_rpi $ mix compile
** (Mix.Config.LoadError) could not load config ../../config/config.exs
    ** (Code.LoadError) could not load /home/config/config.exs
    (elixir) lib/code.ex:657: Code.find_file/2
    (elixir) lib/code.ex:295: Code.eval_file/2
    (mix) lib/mix/config.ex:161: Mix.Config.read!/1
    (mix) lib/mix/tasks/loadconfig.ex:36: Mix.Tasks.Loadconfig.load/1
    (mix) lib/mix/tasks/loadconfig.ex:27: Mix.Tasks.Loadconfig.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:57: Mix.CLI.run_task/2
```

I guess the problem is in mix.exs

```
def project do
    [app: :gpio_rpi,
      version: "0.1.0",
      build_path: "../../_build",
      config_path: "../../config/config.exs",
      deps_path: "../../deps",
      lockfile: "../../mix.lock",
      elixir: "~> 1.2",
      name: "gpio_rpi",
      description: description(),
      package: package(),
      source_url: "https://github.com/Hermanverschooten/gpio_rpi",
      compilers: [:elixir_make] ++ Mix.compilers,
      make_clean: ["clean"],
      docs: [extras: ["README.md"]],
      aliases: ["docs": ["docs", &copy_images/1]],
      build_embedded: Mix.env == :prod,
      start_permanent: Mix.env == :prod,
      deps: deps]
end
```

Also, you might want to add 'run `mix deps.get`' to the docs in the 'just try it out' section.  I changed the paths in mix.exs and the compile worked.

**Comment by Hermanverschooten** [comment]
I already did this before publishing to hex, but I forgot to push the change. Thanks for reminding me.
